### ISSUE TITLE
Mathematical principles on "weight"

### ISSUE THREAD

**Issue by Scrantu** [morteza/weighted-metapath2vec#2]
While appreciating your work very much, I want to know how the edge weights affect the metapath2vec in your implementation. It will be nice if u could offer more details to me.

**Comment by morteza** [comment]
Thanks for your interest @Scrantu.

Sorry for the lack of documentations, this is actually an ongoing and incomplete project. I haven't really had the time to complete the work yet. Nevertheless, I can explain the steps I took in my own use case.

Briefly, there is only a slight modification to the original metapath2vec and that is regarding how walks are generated (step 1 below).

Given a heterogeneous hyper-graph with weighted hyper-edges:

1. First, create a list of random walks following specific metapath patterns (e.g., $V^{(2)} \rightarrow V^{(1)} \rightarrow V^{(2)}$). The sampling process is weighted by the edge weights. That is, the probability of picking the next node in a walk is weighted by the connected edges. So the probability of a walk appearing is based on its cumulative weight. Also, random walks can start from any nodes—only constrained by the metapaths, the total number of random walks, and the maximum number of iterations on all nodes. This is implemented in the [`weighted_random_walk`](https://github.com/morteza/weighted-metapath2vec/blob/main/weighted_metapath2vec/model.py) function.

2. Then, apply the usual word2vec-like embeddings to encode the extracted random walks. Here, I used similar implementation to the [Metapath2Vec from StellarGraph](https://stellargraph.readthedocs.io/en/stable/demos/embeddings/metapath2vec-embeddings.html).
I then used the node embeddings (i.e., `wv`) for the downstream tasks. This step is implemented in the [`WeightedMetapath2VecModel`](https://github.com/morteza/weighted-metapath2vec/blob/main/weighted_metapath2vec/model.py) class.

Hope this gives an idea of the process. I will let you know once the preprint with mathematical formulations is ready.

**Comment by Scrantu** [comment]
> Thanks for your interest @Scrantu.
> 
> Sorry for the lack of documentations, this is actually an ongoing and incomplete project. I haven't really had the time to complete the work yet. Nevertheless, I can explain the steps I took in my own use case.
> 
> Briefly, there is only a slight modification to the original metapath2vec and that is regarding how walks are generated (step 1 below).
> 
> Given a heterogeneous hyper-graph with weighted hyper-edges:
> 
> 1. First, create a list of random walks following specific metapath patterns (e.g., V(2)→V(1)→V(2)). The sampling process is weighted by the edge weights. That is, the probability of picking the next node in a walk is weighted by the connected edges. So the probability of a walk appearing is based on its cumulative weight. Also, random walks can start from any nodes—only constrained by the metapaths, the total number of random walks, and the maximum number of iterations on all nodes. This is implemented in the [`weighted_random_walk`](https://github.com/morteza/weighted-metapath2vec/blob/main/weighted_metapath2vec/model.py) function.
> 2. Then, apply the usual word2vec-like embeddings to encode the extracted random walks. Here, I used similar implementation to the [Metapath2Vec from StellarGraph](https://stellargraph.readthedocs.io/en/stable/demos/embeddings/metapath2vec-embeddings.html).
>    I then used the node embeddings (i.e., `wv`) for the downstream tasks. This step is implemented in the [`WeightedMetapath2VecModel`](https://github.com/morteza/weighted-metapath2vec/blob/main/weighted_metapath2vec/model.py) class.
> 
> Hope this gives an idea of the process. I will let you know once the preprint with mathematical formulations is ready.

Thanks a lot, I will definitely stick to your great work.
